# Configuração geral
semi: true
trailingComma: "all"
singleQuote: true
printWidth: 100
tabWidth: 2

# Configurações específicas por tipo de arquivo
overrides:
  - files: "*.{js,jsx,ts,tsx}"
    options:
      printWidth: 100
      tabWidth: 2
      semi: true

  - files: "*.{css,scss,less}"
    options:
      printWidth: 120
      tabWidth: 2

  - files: "*.{json,yml,yaml}"
    options:
      printWidth: 80
      tabWidth: 2

  - files: "*.md"
    options:
      printWidth: 80
      proseWrap: "always"
