#!/bin/bash

# 🧪 SCRIPT DE TESTE FINAL - PREVIEW DO EDITOR

echo "═══════════════════════════════════════════════════════════"
echo "🧪 TESTE FINAL - PREVIEW DO EDITOR"
echo "═══════════════════════════════════════════════════════════"
echo ""

# Verificar se o servidor está rodando
echo "🔍 Verificando se servidor está rodando..."
if ! curl -s http://localhost:5173 > /dev/null 2>&1; then
    echo "❌ Servidor não está rodando!"
    echo "   Execute: npm run dev"
    exit 1
fi
echo "✅ Servidor rodando em http://localhost:5173"
echo ""

# Resumo das correções
echo "═══════════════════════════════════════════════════════════"
echo "✅ CORREÇÕES IMPLEMENTADAS"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "1. ⏱️  Timeout de 5s no useComponentConfiguration"
echo "   → Previne loading infinito"
echo "   → Arquivo: src/hooks/useComponentConfiguration.ts"
echo ""
echo "2. 🛡️  Fallback reforçado no ConfigurationAPI"
echo "   → Nunca falha, sempre retorna config válida"
echo "   → Arquivo: src/services/ConfigurationAPI.ts"
echo ""
echo "3. 🐛 Logs de debug críticos"
echo "   → LiveRuntimePreview: log de renderização"
echo "   → QuizAppConnected: log de props recebidas"
echo ""

# Instruções de teste
echo "═══════════════════════════════════════════════════════════"
echo "📋 INSTRUÇÕES DE TESTE"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "1. Abra o navegador em: http://localhost:5173/editor"
echo ""
echo "2. Abra o DevTools (F12) e vá para a aba Console"
echo ""
echo "3. Limpe o console (Ctrl+L) e recarregue a página (F5)"
echo ""
echo "4. Procure pelos seguintes logs:"
echo ""
echo "   ✅ ESPERADO VER:"
echo "   🎨 LiveRuntimePreview RENDERIZADO"
echo "   🎯 QuizAppConnected RENDERIZADO"
echo "   🔄 Loading configuration for quiz-global-config"
echo "   🔄 Loading configuration for quiz-theme-config"
echo "   ⚙️ Using default configuration: ..."
echo "   ✅ Configuration loaded for ..."
echo ""
echo "   ❌ NÃO DEVE APARECER:"
echo "   ⚠️ Loading timeout (significa que algo travou)"
echo "   ❌ Error loading configuration (sem fallback)"
echo ""

# Verificar se preview renderiza
echo "═══════════════════════════════════════════════════════════"
echo "🎨 VERIFICAÇÃO DO PREVIEW"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "✅ O preview deve aparecer na COLUNA DA DIREITA"
echo ""
echo "✅ Deve mostrar a primeira step do quiz"
echo ""
echo "✅ Deve atualizar quando você mudar propriedades no editor"
echo ""
echo "✅ Deve ter um rodapé com 'Live Runtime v{X}' e '{N} steps'"
echo ""

# Comandos úteis
echo "═══════════════════════════════════════════════════════════"
echo "🛠️ COMANDOS ÚTEIS"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "📊 Ver logs do servidor:"
echo "   tail -f /workspaces/quiz-flow-pro-verso/build-output.txt"
echo ""
echo "🔄 Reiniciar servidor:"
echo "   Ctrl+C no terminal do 'npm run dev'"
echo "   npm run dev"
echo ""
echo "🧹 Limpar cache do navegador:"
echo "   DevTools → Application → Clear Storage → Clear site data"
echo ""
echo "📸 Capturar logs do console:"
echo "   DevTools → Console → Right-click → Save as..."
echo ""

# Próximos passos
echo "═══════════════════════════════════════════════════════════"
echo "🎯 PRÓXIMOS PASSOS"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "1. Siga as instruções de teste acima"
echo ""
echo "2. Se o preview NÃO aparecer:"
echo "   → Copie TODOS os logs do console"
echo "   → Me envie para análise"
echo "   → Incluir erros em vermelho"
echo ""
echo "3. Se o preview APARECER mas não funcionar:"
echo "   → Descreva o comportamento"
echo "   → Copie logs relacionados"
echo "   → Me envie para ajuste fino"
echo ""
echo "4. Se tudo funcionar:"
echo "   → ✅ SUCESSO! Preview está funcionando!"
echo "   → Teste mudanças no editor"
echo "   → Confirme que refletem no preview"
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "✅ PRONTO PARA TESTE!"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "🌐 Abra: http://localhost:5173/editor"
echo ""
echo "🤖 Aguardando seu feedback..."
echo ""
