#!/bin/bash
# Script para testar auto-advance nas etapas 2-11

echo "🔍 Testando AUTO-ADVANCE nas etapas 2-11..."
echo ""

# Verificar se o servidor está rodando
if ! curl -s http://localhost:8080 > /dev/null; then
    echo "❌ Servidor não está rodando em localhost:8080"
    echo "Execute: npm run dev"
    exit 1
fi

echo "✅ Servidor rodando"
echo ""

# Abrir o editor no navegador
echo "📱 Abrindo editor no navegador..."
"$BROWSER" "http://localhost:8080/editor?template=quiz21StepsComplete" &

echo ""
echo "🧪 Instruções de teste - AUTO-ADVANCE (Steps 2-11):"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "📋 O que é o AUTO-ADVANCE?"
echo "═══════════════════════════════════════════════════════════════"
echo "Quando você seleciona o número mínimo de opções requeridas,"
echo "o quiz deve avançar automaticamente após 1.5 segundos."
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "🎯 COMO TESTAR:"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "1️⃣  Entre no modo PREVIEW:"
echo "   • Abra o Console do navegador (F12)"
echo "   • Digite: window.__editorMode.setViewMode('preview')"
echo "   • Pressione Enter"
echo ""
echo "2️⃣  Navegue até a ETAPA 2:"
echo "   • Título: 'Pergunta 1 de 10'"
echo "   • Subtítulo: 'QUAL O SEU TIPO DE ROUPA FAVORITA?'"
echo "   • 8 opções com imagens"
echo "   • Requer: 3 seleções"
echo ""
echo "3️⃣  TESTE o auto-advance:"
echo "   a) Selecione 1 opção → Botão 'Avançar' continua DESABILITADO"
echo "   b) Selecione 2ª opção → Botão continua DESABILITADO"
echo "   c) Selecione 3ª opção → Botão fica HABILITADO (dourado)"
echo "   d) AGUARDE 1.5 segundos → Deve AVANÇAR automaticamente"
echo ""
echo "4️⃣  REPITA para etapas 3-11:"
echo "   • Etapa 3: 'Pergunta 2 de 10' (3 de 8 opções)"
echo "   • Etapa 4: 'Pergunta 3 de 10' (3 de 8 opções)"
echo "   • Etapa 5: 'Pergunta 4 de 10' (3 de 8 opções)"
echo "   • Etapa 6: 'Pergunta 5 de 10' (3 de 8 opções)"
echo "   • Etapa 7: 'Pergunta 6 de 10' (3 de 8 opções)"
echo "   • Etapa 8: 'Pergunta 7 de 10' (3 de 8 opções)"
echo "   • Etapa 9: 'Pergunta 8 de 10' (3 de 8 opções)"
echo "   • Etapa 10: 'Pergunta 9 de 10' (3 de 8 opções)"
echo "   • Etapa 11: 'Pergunta 10 de 10' (3 de 8 opções)"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "✅ COMPORTAMENTO ESPERADO:"
echo "═══════════════════════════════════════════════════════════════"
echo "• Antes de 3 seleções: Botão DESABILITADO (cinza)"
echo "• Após 3 seleções: Botão HABILITADO (dourado)"
echo "• Após 1.5s: Avança AUTOMATICAMENTE para próxima etapa"
echo "• Usuário pode clicar no botão ANTES dos 1.5s (manual)"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "❌ COMPORTAMENTO INCORRETO:"
echo "═══════════════════════════════════════════════════════════════"
echo "• Avança antes de 3 seleções"
echo "• Não avança automaticamente após 1.5s"
echo "• Botão não fica habilitado com 3 seleções"
echo "• Timer não é cancelado ao clicar manualmente"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "🔍 DEBUG:"
echo "═══════════════════════════════════════════════════════════════"
echo "Se o auto-advance não funcionar, verifique no console:"
echo "• Errors relacionados a 'contextData'"
echo "• Warnings sobre 'goToNext' ou 'onNext'"
echo "• Network errors (imagens não carregando)"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "📊 CONFIGURAÇÃO TÉCNICA:"
echo "═══════════════════════════════════════════════════════════════"
echo "• autoAdvance: true"
echo "• autoAdvanceDelay: 1500 (ms)"
echo "• minSelections: 3"
echo "• maxSelections: 3"
echo "• multipleSelection: true"
echo ""
echo "═══════════════════════════════════════════════════════════════"
