// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Acesso direto às variáveis de ambiente do Vite
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || '';
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || '';

// Log para debug (apenas em DEV)
if (import.meta.env.DEV) {
  console.log('[Supabase Client] URL:', SUPABASE_URL ? '✅ configurado' : '❌ vazio');
  console.log('[Supabase Client] KEY:', SUPABASE_ANON_KEY ? '✅ configurado' : '❌ vazio');
}

let supabaseInstance: SupabaseClient<Database> | null = null;

function getClient(): SupabaseClient<Database> {
  if (supabaseInstance) return supabaseInstance;
  
  if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
    console.error('[Supabase] Variáveis de ambiente não configuradas!');
    console.error('VITE_SUPABASE_URL:', SUPABASE_URL || 'VAZIO');
    console.error('VITE_SUPABASE_PUBLISHABLE_KEY:', SUPABASE_ANON_KEY ? '***' : 'VAZIO');
    throw new Error('Supabase não configurado: VITE_SUPABASE_URL e VITE_SUPABASE_PUBLISHABLE_KEY são obrigatórios');
  }
  
  supabaseInstance = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true,
    },
  });
  
  return supabaseInstance;
}

export const supabase = getClient();

export function setSupabaseCredentials(url: string, anonKey: string) {
  try {
    if (typeof localStorage !== 'undefined') {
      localStorage.setItem('supabase:url', String(url || ''));
      localStorage.setItem('supabase:key', String(anonKey || ''));
    }
  } catch {}
}
