// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Acesso direto às variáveis de ambiente do Vite
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || '';
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || '';

// Log para debug (apenas em DEV)
if (import.meta.env.DEV) {
  console.log('[Supabase Client] URL:', SUPABASE_URL ? '✅ configurado' : '❌ vazio');
  console.log('[Supabase Client] KEY:', SUPABASE_ANON_KEY ? '✅ configurado' : '❌ vazio');
}

let supabaseInstance: SupabaseClient<Database> | null = null;

function getClient(): SupabaseClient<Database> {
  if (supabaseInstance) return supabaseInstance;
  
  if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
    console.warn('[Supabase] Variáveis de ambiente não configuradas - usando mock client');
    // Return a mock client instead of throwing
    return createMockClient() as unknown as SupabaseClient<Database>;
  }
  
  supabaseInstance = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true,
    },
  });
  
  return supabaseInstance;
}

// Mock client para quando as variáveis de ambiente não estão disponíveis
function createMockClient() {
  const ok: any = { data: null, error: null };
  const chain = () => ({
    select: async () => ok,
    upsert: async () => ok,
    insert: async () => ok,
    update: async () => ok,
    delete: async () => ok,
    eq: () => chain(),
    order: () => chain(),
    limit: () => chain(),
    single: async () => ok,
    maybeSingle: async () => ok,
  });

  return {
    from: () => chain(),
    auth: {
      onAuthStateChange: (_cb: any) => ({ data: { subscription: { unsubscribe: () => {} } } }),
      getSession: async () => ({ data: { session: null }, error: null }),
      getUser: async () => ({ data: { user: null }, error: null }),
      signInWithPassword: async () => ok,
      signUp: async () => ({ data: { user: null }, error: null }),
      signOut: async () => ok,
      resetPasswordForEmail: async () => ok,
      signInWithOAuth: async () => ({ data: { url: '' }, error: null }),
      updateUser: async () => ok,
      refreshSession: async () => ({ data: { user: null, session: null }, error: null }),
    },
    storage: {
      from: () => ({
        upload: async () => ok,
        getPublicUrl: () => ({ data: { publicUrl: '' } }),
        remove: async () => ok,
        list: async () => ({ data: [], error: null }),
      }),
    },
    channel: () => ({
      on: () => ({ subscribe: () => ({}) }),
      subscribe: () => ({}),
    }),
  };
}

export const supabase = getClient();

export function setSupabaseCredentials(url: string, anonKey: string) {
  try {
    if (typeof localStorage !== 'undefined') {
      localStorage.setItem('supabase:url', String(url || ''));
      localStorage.setItem('supabase:key', String(anonKey || ''));
    }
  } catch {}
}
