// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = (import.meta as any)?.env?.VITE_SUPABASE_URL as string;
const SUPABASE_ANON_KEY = (import.meta as any)?.env?.VITE_SUPABASE_ANON_KEY as string;
const DISABLE_SUPABASE = ((import.meta as any)?.env?.VITE_DISABLE_SUPABASE === 'true');

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Safe access to localStorage with fallback
const getStorage = () => {
  try {
    return typeof localStorage !== 'undefined' ? localStorage : undefined;
  } catch {
    return undefined;
  }
};

function buildMock() {
  const ok: any = { data: null, error: null };
  const chain = () => ({
    select: async () => ok,
    upsert: async () => ok,
    insert: async () => ok,
    update: async () => ok,
    delete: async () => ok,
    eq: () => chain(),
    order: () => chain(),
    single: async () => ok,
    maybeSingle: async () => ok,
  });

  const subscription = { unsubscribe: () => {} };

  return {
    from: () => chain(),
    auth: {
      onAuthStateChange: (_cb: any) => ({ data: { subscription } }),
      getSession: async () => ({ data: { session: null }, error: null }),
      getUser: async () => ({ data: { user: null }, error: null }),
      signInWithPassword: async () => ok,
      signUp: async () => ({ data: { user: null }, error: null }),
      signOut: async () => ok,
      resetPasswordForEmail: async () => ok,
      signInWithOAuth: async (_opts: any) => ({ data: { url: '' }, error: null }),
      resend: async (_opts: any) => ok,
    },
    storage: {
      from: () => ({
        upload: async () => ok,
        getPublicUrl: (_path: string) => ({ data: { publicUrl: '' }, error: null }),
        remove: async () => ok,
        list: async () => ({ data: [], error: null }),
      }),
    },
  } as any;
}

const readLs = (key: string): string => {
  try {
    return typeof localStorage !== 'undefined' ? (localStorage.getItem(key) || '') : '';
  } catch { return ''; }
};

const LS_URL = readLs('supabase:url') || readLs('SB_URL');
const LS_KEY = readLs('supabase:key') || readLs('SB_ANON');

const EFFECTIVE_URL = SUPABASE_URL || LS_URL;
const EFFECTIVE_KEY = SUPABASE_ANON_KEY || LS_KEY;

const hasEnv = !!(EFFECTIVE_URL && EFFECTIVE_KEY);

export const supabase = (hasEnv && !DISABLE_SUPABASE)
  ? createClient<Database>(EFFECTIVE_URL, EFFECTIVE_KEY, {
      auth: {
        storage: getStorage(),
        persistSession: true,
        autoRefreshToken: true,
        detectSessionInUrl: true,
      },
    })
  : (buildMock() as any);

export function setSupabaseCredentials(url: string, anonKey: string) {
  try {
    if (typeof localStorage !== 'undefined') {
      localStorage.setItem('supabase:url', String(url || ''));
      localStorage.setItem('supabase:key', String(anonKey || ''));
    }
  } catch {}
}
