// This file is auto-generated by the GitHub Action 'Generate Supabase Types'.
// Do not edit manually. Run the workflow to refresh types.

// Placeholder until CI generates real types.
export type Database = Record<string, never>;
