import { BlockDefinition } from '@/types/editor';
import { AlignLeft, Heading, Image, Minus, Square, Type } from 'lucide-react';

// Import real components instead of placeholder
import ImageDisplayInlineBlock from '@/components/blocks/inline/ImageDisplayInlineBlock';
// import StyleCardInlineBlock from "@/components/blocks/inline/StyleCardInlineBlock";
import QuizOptionsGridBlock from '@/components/blocks/quiz/QuizOptionsGridBlock';
import BadgeInlineBlock from '@/components/editor/blocks/BadgeInlineBlock';
import DecorativeBarInlineBlock from '@/components/editor/blocks/DecorativeBarInlineBlock';
import FinalStepEditor from '@/components/editor/blocks/FinalStepEditor';
import FormInputBlock from '@/components/editor/blocks/FormInputBlock';
import HeadingInlineBlock from '@/components/editor/blocks/HeadingInlineBlock';
import LegalNoticeInlineBlock from '@/components/editor/blocks/LegalNoticeInlineBlock';
import QuizIntroHeaderBlock from '@/components/editor/blocks/QuizIntroHeaderBlock';
import QuizProgressBlock from '@/components/editor/blocks/QuizProgressBlock';
import QuizResultsEditor from '@/components/editor/blocks/QuizResultsEditor';
import SpacerInlineBlock from '@/components/editor/blocks/SpacerInlineBlock';
import StyleResultsEditor from '@/components/editor/blocks/StyleResultsEditor';
import TextInlineBlock from '@/components/editor/blocks/TextInlineBlock';

export const blockDefinitions: BlockDefinition[] = [
  {
    type: 'heading',
    name: 'Título',
    description: 'Título principal com diferentes níveis (H1-H6)',
    category: 'Text',
    icon: Heading,
    component: HeadingInlineBlock, // ✅ CONECTADO ao componente correto
    properties: {
      content: {
        type: 'string',
        default: 'Título Principal',
        label: 'Conteúdo',
        description: 'Texto do título',
      },
      level: {
        type: 'select',
        default: 'h2',
        label: 'Nível do Título',
        options: [
          { value: 'h1', label: 'Título 1 (H1)' },
          { value: 'h2', label: 'Título 2 (H2)' },
          { value: 'h3', label: 'Título 3 (H3)' },
          { value: 'h4', label: 'Título 4 (H4)' },
          { value: 'h5', label: 'Título 5 (H5)' },
          { value: 'h6', label: 'Título 6 (H6)' },
        ],
      },
      textAlign: {
        type: 'select',
        default: 'left',
        label: 'Alinhamento',
        options: [
          { value: 'left', label: 'Esquerda' },
          { value: 'center', label: 'Centro' },
          { value: 'right', label: 'Direita' },
        ],
      },
      fontWeight: {
        type: 'select',
        default: 'bold',
        label: 'Peso da Fonte',
        options: [
          { value: 'light', label: 'Leve' },
          { value: 'normal', label: 'Normal' },
          { value: 'medium', label: 'Médio' },
          { value: 'semibold', label: 'Semi-negrito' },
          { value: 'bold', label: 'Negrito' },
          { value: 'extrabold', label: 'Extra-negrito' },
        ],
      },
      color: {
        type: 'color',
        default: '#1f2937',
        label: 'Cor do Texto',
        description: 'Cor do texto do título',
      },
      backgroundColor: {
        type: 'color',
        default: 'transparent',
        label: 'Cor de Fundo',
        description: 'Cor de fundo do título',
      },
      maxWidth: {
        type: 'select',
        default: 'full',
        label: 'Largura Máxima',
        options: [
          { value: 'sm', label: 'Pequena' },
          { value: 'md', label: 'Média' },
          { value: 'lg', label: 'Grande' },
          { value: 'xl', label: 'Extra Grande' },
          { value: '2xl', label: '2X Grande' },
          { value: 'full', label: 'Total' },
        ],
      },
    },
    label: 'Título',
    defaultProps: {
      content: 'Título Principal',
      level: 'h2',
      textAlign: 'left',
      fontWeight: 'bold',
      color: '#1f2937',
      backgroundColor: 'transparent',
      maxWidth: 'full',
    },
  },
  {
    type: 'headline',
    name: 'Título Legado',
    description: 'Título principal e subtítulo (versão legada)',
    category: 'Text',
    icon: Type,
    component: TextInlineBlock, // ✅ CONECTADO ao componente real
    properties: {
      title: {
        type: 'string',
        default: 'Novo Título',
        label: 'Título',
        description: 'Título principal',
      },
      subtitle: {
        type: 'string',
        default: '',
        label: 'Subtítulo',
        description: 'Subtítulo opcional',
      },
      alignment: {
        type: 'select',
        default: 'left',
        label: 'Alinhamento',
        options: [
          { value: 'left', label: 'Esquerda' },
          { value: 'center', label: 'Centro' },
          { value: 'right', label: 'Direita' },
          { value: 'justify', label: 'Justificado' },
        ],
      },
    },
    label: 'Título Legado',
    defaultProps: {
      title: 'Novo Título',
      subtitle: '',
      alignment: 'left',
    },
  },
  {
    type: 'text',
    name: 'Texto',
    description: 'Parágrafo de texto simples',
    category: 'Text',
    icon: AlignLeft,
    component: TextInlineBlock, // ✅ CONECTADO ao componente real
    properties: {
      text: {
        type: 'textarea',
        default: 'Digite seu texto aqui...',
        label: 'Texto',
        description: 'Conteúdo do texto',
      },
      fontSize: {
        type: 'select',
        default: '1rem',
        label: 'Tamanho da fonte',
        options: [
          { value: '0.875rem', label: 'Pequeno' },
          { value: '1rem', label: 'Normal' },
          { value: '1.125rem', label: 'Médio' },
          { value: '1.25rem', label: 'Grande' },
          { value: '1.5rem', label: 'Extra Grande' },
        ],
      },
      alignment: {
        type: 'select',
        default: 'left',
        label: 'Alinhamento',
        options: [
          { value: 'left', label: 'Esquerda' },
          { value: 'center', label: 'Centro' },
          { value: 'right', label: 'Direita' },
          { value: 'justify', label: 'Justificado' },
        ],
      },
    },
    label: 'Texto',
    defaultProps: {
      text: 'Digite seu texto aqui...',
      fontSize: '1rem',
      alignment: 'left',
    },
  },

  {
    type: 'text-inline',
    name: 'Texto Inline',
    description: 'Componente de texto com propriedades editáveis completas',
    category: 'Text',
    icon: AlignLeft,
    component: TextInlineBlock,
    properties: {
      content: {
        type: 'textarea',
        default: 'Digite seu texto aqui...',
        label: 'Conteúdo',
        description: 'Texto do componente (suporte HTML)',
      },
      text: {
        type: 'textarea',
        default: 'Digite seu texto aqui...',
        label: 'Texto Simples',
        description: 'Versão em texto puro',
      },
      fontSize: {
        type: 'select',
        default: 'text-base',
        label: 'Tamanho da Fonte',
        options: [
          { value: 'text-xs', label: 'Extra Pequeno' },
          { value: 'text-sm', label: 'Pequeno' },
          { value: 'text-base', label: 'Normal' },
          { value: 'text-lg', label: 'Médio' },
          { value: 'text-xl', label: 'Grande' },
          { value: 'text-2xl', label: 'Extra Grande' },
          { value: 'text-3xl', label: '2X Grande' },
          { value: 'text-4xl', label: '3X Grande' },
          { value: 'text-5xl', label: '4X Grande' },
        ],
      },
      fontWeight: {
        type: 'select',
        default: 'font-normal',
        label: 'Peso da Fonte',
        options: [
          { value: 'font-light', label: 'Leve' },
          { value: 'font-normal', label: 'Normal' },
          { value: 'font-medium', label: 'Médio' },
          { value: 'font-semibold', label: 'Semi-negrito' },
          { value: 'font-bold', label: 'Negrito' },
          { value: 'font-extrabold', label: 'Extra-negrito' },
        ],
      },
      fontFamily: {
        type: 'select',
        default: 'Inter, sans-serif',
        label: 'Família da Fonte',
        options: [
          { value: 'Inter, sans-serif', label: 'Inter (Sans-serif)' },
          { value: 'Playfair Display, serif', label: 'Playfair Display (Serif)' },
          { value: 'Georgia, serif', label: 'Georgia (Serif)' },
          { value: 'Arial, sans-serif', label: 'Arial (Sans-serif)' },
        ],
      },
      textAlign: {
        type: 'select',
        default: 'text-left',
        label: 'Alinhamento',
        options: [
          { value: 'text-left', label: 'Esquerda' },
          { value: 'text-center', label: 'Centro' },
          { value: 'text-right', label: 'Direita' },
          { value: 'text-justify', label: 'Justificado' },
        ],
      },
      color: {
        type: 'color',
        default: '#1F2937',
        label: 'Cor do Texto',
      },
      backgroundColor: {
        type: 'color',
        default: 'transparent',
        label: 'Cor de Fundo',
      },
      lineHeight: {
        type: 'select',
        default: '1.5',
        label: 'Altura da Linha',
        options: [
          { value: '1', label: '1.0' },
          { value: '1.2', label: '1.2' },
          { value: '1.5', label: '1.5' },
          { value: '1.7', label: '1.7' },
          { value: '2', label: '2.0' },
        ],
      },
      marginTop: {
        type: 'number',
        default: 0,
        label: 'Margem Superior (px)',
        min: 0,
        max: 100,
      },
      marginBottom: {
        type: 'number',
        default: 16,
        label: 'Margem Inferior (px)',
        min: 0,
        max: 100,
      },
      containerWidth: {
        type: 'select',
        default: 'medium',
        label: 'Largura do Container',
        options: [
          { value: 'small', label: 'Pequeno' },
          { value: 'medium', label: 'Médio' },
          { value: 'large', label: 'Grande' },
          { value: 'full', label: 'Total' },
        ],
      },
    },
    label: 'Texto Inline',
    defaultProps: {
      content: 'Digite seu texto aqui...',
      text: 'Digite seu texto aqui...',
      fontSize: 'text-base',
      fontWeight: 'font-normal',
      fontFamily: 'Inter, sans-serif',
      textAlign: 'text-left',
      color: '#1F2937',
      backgroundColor: 'transparent',
      lineHeight: '1.5',
      marginTop: 0,
      marginBottom: 16,
      containerWidth: 'medium',
    },
  },

  {
    type: 'heading-inline',
    name: 'Título Inline',
    description: 'Componente de título com propriedades editáveis completas',
    category: 'Text',
    icon: Heading,
    component: HeadingInlineBlock,
    properties: {
      text: {
        type: 'string',
        default: 'Título Principal',
        label: 'Texto do Título',
      },
      level: {
        type: 'select',
        default: 'h2',
        label: 'Nível do Título',
        options: [
          { value: 'h1', label: 'H1 - Título Principal' },
          { value: 'h2', label: 'H2 - Título Secundário' },
          { value: 'h3', label: 'H3 - Subtítulo' },
          { value: 'h4', label: 'H4 - Título Menor' },
          { value: 'h5', label: 'H5 - Título Pequeno' },
          { value: 'h6', label: 'H6 - Título Mínimo' },
        ],
      },
      fontSize: {
        type: 'select',
        default: 'text-2xl',
        label: 'Tamanho da Fonte',
        options: [
          { value: 'text-lg', label: 'Grande' },
          { value: 'text-xl', label: 'Extra Grande' },
          { value: 'text-2xl', label: '2X Grande' },
          { value: 'text-3xl', label: '3X Grande' },
          { value: 'text-4xl', label: '4X Grande' },
          { value: 'text-5xl', label: '5X Grande' },
        ],
      },
      fontWeight: {
        type: 'select',
        default: 'font-bold',
        label: 'Peso da Fonte',
        options: [
          { value: 'font-normal', label: 'Normal' },
          { value: 'font-medium', label: 'Médio' },
          { value: 'font-semibold', label: 'Semi-negrito' },
          { value: 'font-bold', label: 'Negrito' },
          { value: 'font-extrabold', label: 'Extra-negrito' },
        ],
      },
      textAlign: {
        type: 'select',
        default: 'text-center',
        label: 'Alinhamento',
        options: [
          { value: 'text-left', label: 'Esquerda' },
          { value: 'text-center', label: 'Centro' },
          { value: 'text-right', label: 'Direita' },
        ],
      },
      color: {
        type: 'color',
        default: '#432818',
        label: 'Cor do Texto',
      },
      backgroundColor: {
        type: 'color',
        default: 'transparent',
        label: 'Cor de Fundo',
      },
      marginTop: {
        type: 'number',
        default: 0,
        label: 'Margem Superior (px)',
        min: 0,
        max: 100,
      },
      marginBottom: {
        type: 'number',
        default: 24,
        label: 'Margem Inferior (px)',
        min: 0,
        max: 100,
      },
    },
    label: 'Título Inline',
    defaultProps: {
      text: 'Título Principal',
      level: 'h2',
      fontSize: 'text-2xl',
      fontWeight: 'font-bold',
      textAlign: 'text-center',
      color: '#432818',
      backgroundColor: 'transparent',
      marginTop: 0,
      marginBottom: 24,
    },
  },

  {
    type: 'button-inline',
    name: 'Botão Inline',
    description: 'Componente de botão com propriedades editáveis completas',
    category: 'Interactive',
    icon: Square,
    component: BadgeInlineBlock,
    properties: {
      text: {
        type: 'string',
        default: 'Clique Aqui',
        label: 'Texto do Botão',
      },
      variant: {
        type: 'select',
        default: 'primary',
        label: 'Variante',
        options: [
          { value: 'primary', label: 'Primário' },
          { value: 'secondary', label: 'Secundário' },
          { value: 'outline', label: 'Contorno' },
          { value: 'ghost', label: 'Fantasma' },
          { value: 'cta', label: 'Call to Action' },
        ],
      },
      size: {
        type: 'select',
        default: 'medium',
        label: 'Tamanho',
        options: [
          { value: 'small', label: 'Pequeno' },
          { value: 'medium', label: 'Médio' },
          { value: 'large', label: 'Grande' },
          { value: 'xl', label: 'Extra Grande' },
        ],
      },
      fullWidth: {
        type: 'boolean',
        default: false,
        label: 'Largura Total',
      },
      backgroundColor: {
        type: 'color',
        default: '#B89B7A',
        label: 'Cor de Fundo',
      },
      textColor: {
        type: 'color',
        default: '#FFFFFF',
        label: 'Cor do Texto',
      },
      borderColor: {
        type: 'color',
        default: '#B89B7A',
        label: 'Cor da Borda',
      },
      hoverBackgroundColor: {
        type: 'color',
        default: '#A38A69',
        label: 'Cor de Fundo (Hover)',
      },
      disabled: {
        type: 'boolean',
        default: false,
        label: 'Desabilitado',
      },
      borderRadius: {
        type: 'select',
        default: 'rounded-lg',
        label: 'Borda Arredondada',
        options: [
          { value: 'rounded-none', label: 'Nenhuma' },
          { value: 'rounded-sm', label: 'Pequena' },
          { value: 'rounded-md', label: 'Média' },
          { value: 'rounded-lg', label: 'Grande' },
          { value: 'rounded-xl', label: 'Extra Grande' },
          { value: 'rounded-full', label: 'Circular' },
        ],
      },
      fontSize: {
        type: 'select',
        default: 'text-base',
        label: 'Tamanho da Fonte',
        options: [
          { value: 'text-sm', label: 'Pequeno' },
          { value: 'text-base', label: 'Normal' },
          { value: 'text-lg', label: 'Grande' },
          { value: 'text-xl', label: 'Extra Grande' },
        ],
      },
      fontWeight: {
        type: 'select',
        default: 'font-semibold',
        label: 'Peso da Fonte',
        options: [
          { value: 'font-normal', label: 'Normal' },
          { value: 'font-medium', label: 'Médio' },
          { value: 'font-semibold', label: 'Semi-negrito' },
          { value: 'font-bold', label: 'Negrito' },
        ],
      },
      textAlign: {
        type: 'select',
        default: 'text-center',
        label: 'Alinhamento',
        options: [
          { value: 'text-left', label: 'Esquerda' },
          { value: 'text-center', label: 'Centro' },
          { value: 'text-right', label: 'Direita' },
        ],
      },
      marginTop: {
        type: 'number',
        default: 0,
        label: 'Margem Superior (px)',
        min: 0,
        max: 100,
      },
      marginBottom: {
        type: 'number',
        default: 16,
        label: 'Margem Inferior (px)',
        min: 0,
        max: 100,
      },
    },
    label: 'Botão Inline',
    defaultProps: {
      text: 'Clique Aqui',
      variant: 'primary',
      size: 'medium',
      fullWidth: false,
      backgroundColor: '#B89B7A',
      textColor: '#FFFFFF',
      borderColor: '#B89B7A',
      hoverBackgroundColor: '#A38A69',
      disabled: false,
      borderRadius: 'rounded-lg',
      fontSize: 'text-base',
      fontWeight: 'font-semibold',
      textAlign: 'text-center',
      marginTop: 0,
      marginBottom: 16,
    },
  },
  {
    type: 'decorative-bar-inline',
    name: 'Barra Decorativa',
    description: 'Barra dourada decorativa com controles de altura e cor',
    category: 'Layout',
    icon: Minus,
    component: DecorativeBarInlineBlock, // ✅ CONECTADO ao componente real
    properties: {
      height: {
        type: 'number',
        default: 4,
        label: 'Altura',
        description: 'Altura da barra em pixels (1-50px)',
        min: 1,
        max: 50,
        step: 1,
      },
      width: {
        type: 'string',
        default: '100%',
        label: 'Largura',
        description: 'Largura da barra',
      },
      color: {
        type: 'color',
        default: '#B89B7A',
        label: 'Cor Principal',
        description: 'Cor da barra decorativa',
      },
      borderRadius: {
        type: 'number',
        default: 3,
        label: 'Borda Arredondada',
        description: 'Raio da borda em pixels (0-25px)',
        min: 0,
        max: 25,
        step: 1,
      },
      marginTop: {
        type: 'number',
        default: 8,
        label: 'Margem Superior',
        description: 'Espaçamento acima da barra (0-100px)',
        min: 0,
        max: 100,
        step: 1,
      },
      marginBottom: {
        type: 'number',
        default: 24,
        label: 'Margem Inferior',
        description: 'Espaçamento abaixo da barra (0-100px)',
        min: 0,
        max: 100,
        step: 1,
      },
      showShadow: {
        type: 'boolean',
        default: true,
        label: 'Mostrar Sombra',
        description: 'Adicionar sombra à barra',
      },
    },
    label: 'Barra Decorativa',
    defaultProps: {
      height: 4,
      width: '100%',
      color: '#B89B7A',
      borderRadius: 3,
      marginTop: 8,
      marginBottom: 24,
      showShadow: true,
    },
  },
  {
    type: 'image',
    name: 'Imagem',
    description: 'Componente de imagem',
    category: 'Media',
    icon: Image,
    component: ImageDisplayInlineBlock, // ✅ CONECTADO ao componente real
    properties: {
      url: {
        type: 'string',
        default: '',
        label: 'URL da imagem',
        description: 'Endereço da imagem',
      },
      alt: {
        type: 'string',
        default: 'Imagem',
        label: 'Texto alternativo',
        description: 'Descrição da imagem para acessibilidade',
      },
      width: {
        type: 'string',
        default: '100%',
        label: 'Largura',
        description: 'Largura da imagem',
      },
      height: {
        type: 'string',
        default: 'auto',
        label: 'Altura',
        description: 'Altura da imagem',
      },
      borderRadius: {
        type: 'string',
        default: '0.5rem',
        label: 'Borda arredondada',
        description: 'Raio da borda',
      },
      objectFit: {
        type: 'select',
        default: 'cover',
        label: 'Ajuste da imagem',
        options: [
          { value: 'cover', label: 'Cobrir' },
          { value: 'contain', label: 'Conter' },
          { value: 'fill', label: 'Preencher' },
          { value: 'none', label: 'Nenhum' },
          { value: 'scale-down', label: 'Reduzir' },
        ],
      },
    },
    label: 'Imagem',
    defaultProps: {
      url: '',
      alt: 'Imagem',
      width: '100%',
      height: 'auto',
      borderRadius: '0.5rem',
      objectFit: 'cover',
    },
  },
  {
    type: 'button',
    name: 'Botão',
    description: 'Botão de ação',
    category: 'Interactive',
    icon: Square,
    component: BadgeInlineBlock, // ✅ CONECTADO ao componente real
    properties: {
      text: {
        type: 'string',
        default: 'Clique aqui',
        label: 'Texto do botão',
        description: 'Texto exibido no botão',
      },
      url: {
        type: 'string',
        default: '#',
        label: 'URL de destino',
        description: 'Link para onde o botão deve levar',
      },
      style: {
        type: 'select',
        default: 'primary',
        label: 'Estilo',
        options: [
          { value: 'primary', label: 'Primário' },
          { value: 'secondary', label: 'Secundário' },
          { value: 'outline', label: 'Contorno' },
          { value: 'ghost', label: 'Fantasma' },
        ],
      },
    },
    label: 'Botão',
    defaultProps: {
      text: 'Clique aqui',
      url: '#',
      style: 'primary',
    },
  },
  {
    type: 'spacer',
    name: 'Espaçador',
    description: 'Espaço em branco vertical',
    category: 'Layout',
    icon: Minus,
    component: SpacerInlineBlock, // ✅ CONECTADO ao componente real
    properties: {
      height: {
        type: 'number',
        default: 40,
        label: 'Altura (px)',
        description: 'Altura do espaçamento em pixels',
      },
    },
    label: 'Espaçador',
    defaultProps: {
      height: 40,
    },
  },
  {
    type: 'quiz-intro-header',
    name: 'Cabeçalho do Quiz',
    description: 'Componente cabeçalho do quiz com propriedades configuráveis',
    category: 'Quiz',
    icon: Type,
    component: QuizIntroHeaderBlock,
    properties: {
      logoUrl: {
        type: 'string',
        default:
          'https://res.cloudinary.com/dqljyf76t/image/upload/v1744911572/LOGO_DA_MARCA_GISELE_r14oz2.webp',
        label: 'URL do Logo',
      },
      logoAlt: {
        type: 'string',
        default: 'Logo',
        label: 'Alt do Logo',
      },
      progressValue: {
        type: 'number',
        default: 0,
        label: 'Progresso (%)',
        min: 0,
        max: 100,
      },
      showProgress: {
        type: 'boolean',
        default: true,
        label: 'Mostrar Progresso',
      },
      backgroundColor: {
        type: 'color',
        default: '#F9F5F1',
        label: 'Cor de Fundo',
      },
      height: {
        type: 'number',
        default: 80,
        label: 'Altura (px)',
        min: 50,
        max: 200,
      },
    },
    label: 'Cabeçalho do Quiz',
    defaultProps: {
      logoUrl:
        'https://res.cloudinary.com/dqljyf76t/image/upload/v1744911572/LOGO_DA_MARCA_GISELE_r14oz2.webp',
      logoAlt: 'Logo',
      progressValue: 0,
      showProgress: true,
      backgroundColor: '#F9F5F1',
      height: 80,
    },
  },

  {
    type: 'form-input',
    name: 'Campo de Formulário',
    description: 'Componente campo de formulário com propriedades configuráveis',
    category: 'Form',
    icon: Type,
    component: FormInputBlock,
    properties: {
      label: {
        type: 'string',
        default: 'Campo de Input',
        label: 'Rótulo',
      },
      placeholder: {
        type: 'string',
        default: 'Digite aqui...',
        label: 'Placeholder',
      },
      required: {
        type: 'boolean',
        default: false,
        label: 'Obrigatório',
      },
      type: {
        type: 'select',
        default: 'text',
        label: 'Tipo',
        options: [
          { value: 'text', label: 'Texto' },
          { value: 'email', label: 'Email' },
          { value: 'tel', label: 'Telefone' },
          { value: 'password', label: 'Senha' },
        ],
      },
      width: {
        type: 'string',
        default: '100%',
        label: 'Largura',
      },
      backgroundColor: {
        type: 'color',
        default: '#FFFFFF',
        label: 'Cor de Fundo',
      },
      borderColor: {
        type: 'color',
        default: '#B89B7A',
        label: 'Cor da Borda',
      },
    },
    label: 'Campo de Formulário',
    defaultProps: {
      label: 'Campo de Input',
      placeholder: 'Digite aqui...',
      required: false,
      type: 'text',
      width: '100%',
      backgroundColor: '#FFFFFF',
      borderColor: '#B89B7A',
    },
  },

  {
    type: 'legal-notice-inline',
    name: 'Aviso Legal',
    description: 'Componente aviso legal com propriedades configuráveis',
    category: 'Text',
    icon: Type,
    component: LegalNoticeInlineBlock,
    properties: {
      privacyText: {
        type: 'string',
        default: 'Política de privacidade',
        label: 'Texto de Privacidade',
      },
      copyrightText: {
        type: 'string',
        default: '© 2025 Todos os direitos reservados',
        label: 'Texto de Copyright',
      },
      termsText: {
        type: 'string',
        default: 'Termos de uso',
        label: 'Texto de Termos',
      },
      fontSize: {
        type: 'select',
        default: 'text-xs',
        label: 'Tamanho da Fonte',
        options: [
          { value: 'text-xs', label: 'Extra Pequeno' },
          { value: 'text-sm', label: 'Pequeno' },
          { value: 'text-base', label: 'Normal' },
        ],
      },
      textAlign: {
        type: 'select',
        default: 'center',
        label: 'Alinhamento',
        options: [
          { value: 'left', label: 'Esquerda' },
          { value: 'center', label: 'Centro' },
          { value: 'right', label: 'Direita' },
        ],
      },
      color: {
        type: 'color',
        default: '#6B7280',
        label: 'Cor do Texto',
      },
      linkColor: {
        type: 'color',
        default: '#B89B7A',
        label: 'Cor dos Links',
      },
    },
    label: 'Aviso Legal',
    defaultProps: {
      privacyText: 'Política de privacidade',
      copyrightText: '© 2025 Todos os direitos reservados',
      termsText: 'Termos de uso',
      fontSize: 'text-xs',
      textAlign: 'center',
      color: '#6B7280',
      linkColor: '#B89B7A',
    },
  },

  {
    type: 'image-display-inline',
    name: 'Imagem Inline',
    description: 'Componente imagem inline com propriedades configuráveis',
    category: 'Media',
    icon: Type,
    component: ImageDisplayInlineBlock,
    properties: {
      src: {
        type: 'string',
        default: '',
        label: 'URL da Imagem',
      },
      alt: {
        type: 'string',
        default: 'Imagem',
        label: 'Texto Alternativo',
      },
      width: {
        type: 'string',
        default: '100%',
        label: 'Largura',
      },
      height: {
        type: 'string',
        default: 'auto',
        label: 'Altura',
      },
      objectFit: {
        type: 'select',
        default: 'cover',
        label: 'Ajuste',
        options: [
          { value: 'cover', label: 'Cobrir' },
          { value: 'contain', label: 'Conter' },
          { value: 'fill', label: 'Preencher' },
          { value: 'none', label: 'Nenhum' },
        ],
      },
      borderRadius: {
        type: 'number',
        default: 8,
        label: 'Borda Arredondada',
        min: 0,
        max: 50,
      },
      shadow: {
        type: 'boolean',
        default: false,
        label: 'Sombra',
      },
      alignment: {
        type: 'select',
        default: 'center',
        label: 'Alinhamento',
        options: [
          { value: 'left', label: 'Esquerda' },
          { value: 'center', label: 'Centro' },
          { value: 'right', label: 'Direita' },
        ],
      },
    },
    label: 'Imagem Inline',
    defaultProps: {
      src: '',
      alt: 'Imagem',
      width: '100%',
      height: 'auto',
      objectFit: 'cover',
      borderRadius: 8,
      shadow: false,
      alignment: 'center',
    },
  },

  {
    type: 'options-grid',
    name: 'Grade de Opções',
    description: 'Componente grade de opções com propriedades configuráveis completas',
    category: 'Quiz',
    icon: Type,
    component: QuizOptionsGridBlock,
    properties: {
      question: {
        type: 'textarea',
        default: 'Qual opção você escolhe?',
        label: 'Pergunta',
      },
      questionId: {
        type: 'string',
        default: 'q1',
        label: 'ID da Questão',
        description: 'Identificador único da questão',
      },
      columns: {
        type: 'select',
        default: '2',
        label: 'Colunas',
        options: [
          { value: '1', label: '1 Coluna' },
          { value: '2', label: '2 Colunas' },
          { value: '3', label: '3 Colunas' },
          { value: '4', label: '4 Colunas' },
        ],
      },
      responsiveColumns: {
        type: 'boolean',
        default: true,
        label: 'Colunas Responsivas',
        description: 'Adaptar número de colunas para dispositivos móveis',
      },
      gap: {
        type: 'number',
        default: 16,
        label: 'Espaçamento',
        min: 0,
        max: 50,
      },
      gridGap: {
        type: 'number',
        default: 8,
        label: 'Espaçamento da Grade',
        min: 0,
        max: 32,
      },
      selectionMode: {
        type: 'select',
        default: 'single',
        label: 'Modo de Seleção',
        options: [
          { value: 'single', label: 'Seleção Única' },
          { value: 'multiple', label: 'Seleção Múltipla' },
        ],
      },
      multipleSelection: {
        type: 'boolean',
        default: false,
        label: 'Seleção Múltipla',
      },
      maxSelections: {
        type: 'number',
        default: 1,
        label: 'Máximo de Seleções',
        min: 1,
        max: 10,
      },
      minSelections: {
        type: 'number',
        default: 1,
        label: 'Mínimo de Seleções',
        min: 1,
        max: 10,
      },
      requiredSelections: {
        type: 'number',
        default: 1,
        label: 'Seleções Obrigatórias',
        min: 1,
        max: 10,
      },
      primaryColor: {
        type: 'color',
        default: '#B89B7A',
        label: 'Cor Principal',
      },
      accentColor: {
        type: 'color',
        default: '#D4C2A8',
        label: 'Cor de Destaque',
      },
      selectedColor: {
        type: 'color',
        default: '#B89B7A',
        label: 'Cor de Seleção',
      },
      hoverColor: {
        type: 'color',
        default: '#D4C2A8',
        label: 'Cor de Hover',
      },
      showImages: {
        type: 'boolean',
        default: true,
        label: 'Mostrar Imagens',
      },
      imagePosition: {
        type: 'select',
        default: 'top',
        label: 'Posição da Imagem',
        options: [
          { value: 'top', label: 'Acima' },
          { value: 'left', label: 'Esquerda' },
          { value: 'right', label: 'Direita' },
          { value: 'background', label: 'Fundo' },
        ],
      },
      imageSize: {
        type: 'range',
        default: 256,
        label: 'Tamanho da Imagem (px)',
        min: 64,
        max: 512,
        step: 16,
      },
      imageWidth: {
        type: 'range',
        default: 256,
        label: 'Largura da Imagem (px)',
        min: 64,
        max: 512,
        step: 16,
      },
      imageHeight: {
        type: 'range',
        default: 256,
        label: 'Altura da Imagem (px)',
        min: 64,
        max: 512,
        step: 16,
      },
      // === CONFIGURAÇÕES DE LAYOUT ===
      layoutOrientation: {
        type: 'select',
        default: 'vertical',
        label: 'Orientação do Layout',
        options: [
          { value: 'vertical', label: 'Vertical' },
          { value: 'horizontal', label: 'Horizontal' },
        ],
      },
      // === CONFIGURAÇÕES DE BORDAS E CORES ===
      showBorders: {
        type: 'boolean',
        default: true,
        label: 'Mostrar Bordas',
      },
      borderWidth: {
        type: 'range',
        default: 2,
        label: 'Espessura da Borda (px)',
        min: 0,
        max: 8,
        step: 1,
      },
      borderColor: {
        type: 'color',
        default: '#E5E7EB',
        label: 'Cor da Borda',
      },
      selectedBorderColor: {
        type: 'color',
        default: '#B89B7A',
        label: 'Cor da Borda (Selecionado)',
      },
      borderRadius: {
        type: 'range',
        default: 8,
        label: 'Raio da Borda (px)',
        min: 0,
        max: 32,
        step: 2,
      },
      // === CONFIGURAÇÕES DE SOMBRAS ===
      showShadows: {
        type: 'boolean',
        default: true,
        label: 'Mostrar Sombras',
      },
      shadowColor: {
        type: 'color',
        default: '#00000020',
        label: 'Cor da Sombra',
      },
      selectedShadowColor: {
        type: 'color',
        default: '#B89B7A40',
        label: 'Cor da Sombra (Selecionado)',
      },
      shadowIntensity: {
        type: 'range',
        default: 3,
        label: 'Intensidade da Sombra',
        min: 0,
        max: 10,
        step: 1,
      },
      // === CONTROLE DE ESCALA ===
      scale: {
        type: 'range',
        default: 100,
        label: 'Escala do Container (%)',
        min: 50,
        max: 110,
        step: 5,
      },
      // === CONFIGURAÇÕES DE CONTEÚDO ===
      contentType: {
        type: 'select',
        default: 'text-and-image',
        label: 'Tipo de Conteúdo',
        options: [
          { value: 'text-only', label: 'Apenas Texto' },
          { value: 'image-only', label: 'Apenas Imagem' },
          { value: 'text-and-image', label: 'Texto e Imagem' },
        ],
      },
      // === CONFIGURAÇÕES DE OPÇÕES (Lista Editável) ===
      options: {
        type: 'array',
        default: [
          { text: 'Opção 1', points: 1, category: '', imageUrl: '' },
          { text: 'Opção 2', points: 1, category: '', imageUrl: '' },
        ],
        label: 'Lista de Opções',
        description: 'Configure as opções de resposta disponíveis',
      },
      validationMessage: {
        type: 'string',
        default: 'Selecione uma opção',
        label: 'Mensagem de Validação',
      },
      progressMessage: {
        type: 'string',
        default: '{selected} de {maxSelections} selecionados',
        label: 'Mensagem de Progresso',
      },
      autoAdvanceOnComplete: {
        type: 'boolean',
        default: false,
        label: 'Avançar Automaticamente',
      },
      autoAdvanceDelay: {
        type: 'number',
        default: 0,
        label: 'Delay do Auto-avanço (ms)',
        min: 0,
        max: 5000,
      },
      instantActivation: {
        type: 'boolean',
        default: true,
        label: 'Ativação Instantânea',
      },
      enableButtonOnlyWhenValid: {
        type: 'boolean',
        default: true,
        label: 'Botão Apenas Quando Válido',
      },
      showValidationFeedback: {
        type: 'boolean',
        default: true,
        label: 'Mostrar Feedback de Validação',
      },
      selectionStyle: {
        type: 'select',
        default: 'border',
        label: 'Estilo de Seleção',
        options: [
          { value: 'border', label: 'Borda' },
          { value: 'background', label: 'Fundo' },
          { value: 'shadow', label: 'Sombra' },
          { value: 'scale', label: 'Escala' },
        ],
      },
      showSelectionCount: {
        type: 'boolean',
        default: true,
        label: 'Mostrar Contador de Seleção',
      },
      allowDeselection: {
        type: 'boolean',
        default: true,
        label: 'Permitir Desseleção',
      },
      trackSelectionOrder: {
        type: 'boolean',
        default: false,
        label: 'Rastrear Ordem de Seleção',
      },
    },
    label: 'Grade de Opções',
    defaultProps: {
      question: 'Qual opção você escolhe?',
      questionId: 'q1',
      columns: '2',
      responsiveColumns: true,
      gap: 16,
      gridGap: 8,
      selectionMode: 'single',
      multipleSelection: false,
      maxSelections: 1,
      minSelections: 1,
      requiredSelections: 1,
      primaryColor: '#B89B7A',
      accentColor: '#D4C2A8',
      selectedColor: '#B89B7A',
      hoverColor: '#D4C2A8',
      showImages: true,
      imagePosition: 'top',
      imageSize: 256,
      imageWidth: 256,
      imageHeight: 256,
      layoutOrientation: 'vertical',
      showBorders: true,
      borderWidth: 2,
      borderColor: '#E5E7EB',
      selectedBorderColor: '#B89B7A',
      borderRadius: 8,
      showShadows: true,
      shadowColor: '#00000020',
      selectedShadowColor: '#B89B7A40',
      shadowIntensity: 3,
      contentType: 'text-and-image',
      options: [
        {
          id: 'option-1',
          text: 'Opção 1',
          points: 1,
          category: 'categoria1',
          imageUrl: '',
        },
        {
          id: 'option-2',
          text: 'Opção 2',
          points: 1,
          category: 'categoria2',
          imageUrl: '',
        },
      ],
      validationMessage: 'Selecione uma opção',
      progressMessage: '{selected} de {maxSelections} selecionados',
      autoAdvanceOnComplete: false,
      autoAdvanceDelay: 0,
      instantActivation: true,
      enableButtonOnlyWhenValid: true,
      showValidationFeedback: true,
      selectionStyle: 'border',
      showSelectionCount: true,
      allowDeselection: true,
      trackSelectionOrder: false,
    },
  },

  {
    type: 'quiz-progress',
    name: 'Progresso do Quiz',
    description: 'Componente progresso do quiz com propriedades configuráveis',
    category: 'Quiz',
    icon: Type,
    component: QuizProgressBlock,
    properties: {
      currentStep: {
        type: 'number',
        default: 1,
        label: 'Etapa Atual',
        min: 1,
        max: 21,
      },
      totalSteps: {
        type: 'number',
        default: 21,
        label: 'Total de Etapas',
        min: 1,
        max: 50,
      },
      showNumbers: {
        type: 'boolean',
        default: true,
        label: 'Mostrar Números',
      },
      showPercentage: {
        type: 'boolean',
        default: true,
        label: 'Mostrar Percentual',
      },
      barColor: {
        type: 'color',
        default: '#B89B7A',
        label: 'Cor da Barra',
      },
      backgroundColor: {
        type: 'color',
        default: '#E5E7EB',
        label: 'Cor de Fundo',
      },
      height: {
        type: 'number',
        default: 8,
        label: 'Altura (px)',
        min: 4,
        max: 20,
      },
      borderRadius: {
        type: 'number',
        default: 4,
        label: 'Borda Arredondada',
        min: 0,
        max: 20,
      },
      animated: {
        type: 'boolean',
        default: true,
        label: 'Animado',
      },
    },
    label: 'Progresso do Quiz',
    defaultProps: {
      currentStep: 1,
      totalSteps: 21,
      showNumbers: true,
      showPercentage: true,
      barColor: '#B89B7A',
      backgroundColor: '#E5E7EB',
      height: 8,
      borderRadius: 4,
      animated: true,
    },
  },

  {
    type: 'quiz-results',
    name: 'Resultados do Quiz',
    description: 'Componente resultados do quiz com propriedades configuráveis',
    category: 'Quiz',
    icon: Type,
    component: QuizResultsEditor,
    properties: {
      title: {
        type: 'string',
        default: 'Seus Resultados',
        label: 'Título',
      },
      showScores: {
        type: 'boolean',
        default: true,
        label: 'Mostrar Pontuações',
      },
      showPercentages: {
        type: 'boolean',
        default: true,
        label: 'Mostrar Percentuais',
      },
      showRanking: {
        type: 'boolean',
        default: false,
        label: 'Mostrar Ranking',
      },
      primaryColor: {
        type: 'color',
        default: '#B89B7A',
        label: 'Cor Principal',
      },
      secondaryColor: {
        type: 'color',
        default: '#D4C2A8',
        label: 'Cor Secundária',
      },
      layout: {
        type: 'select',
        default: 'vertical',
        label: 'Layout',
        options: [
          { value: 'vertical', label: 'Vertical' },
          { value: 'horizontal', label: 'Horizontal' },
          { value: 'grid', label: 'Grade' },
        ],
      },
      showImages: {
        type: 'boolean',
        default: true,
        label: 'Mostrar Imagens',
      },
      animatedEntry: {
        type: 'boolean',
        default: true,
        label: 'Entrada Animada',
      },
    },
    label: 'Resultados do Quiz',
    defaultProps: {
      title: 'Seus Resultados',
      showScores: true,
      showPercentages: true,
      showRanking: false,
      primaryColor: '#B89B7A',
      secondaryColor: '#D4C2A8',
      layout: 'vertical',
      showImages: true,
      animatedEntry: true,
    },
  },

  {
    type: 'style-results',
    name: 'Resultados de Estilo',
    description: 'Componente resultados de estilo com propriedades configuráveis',
    category: 'Quiz',
    icon: Type,
    component: StyleResultsEditor,
    properties: {
      title: {
        type: 'string',
        default: 'Seu Estilo Predominante',
        label: 'Título',
      },
      showAllStyles: {
        type: 'boolean',
        default: false,
        label: 'Mostrar Todos os Estilos',
      },
      showGuideImage: {
        type: 'boolean',
        default: true,
        label: 'Mostrar Guia',
      },
      guideImageUrl: {
        type: 'string',
        default:
          'https://res.cloudinary.com/dqljyf76t/image/upload/v1745071344/GUIA_NATURAL_fzp6fc.webp',
        label: 'URL do Guia',
      },
      primaryStyle: {
        type: 'select',
        default: 'Natural',
        label: 'Estilo Principal',
        options: [
          { value: 'Natural', label: 'Natural' },
          { value: 'Clássico', label: 'Clássico' },
          { value: 'Elegante', label: 'Elegante' },
          { value: 'Contemporâneo', label: 'Contemporâneo' },
          { value: 'Romântico', label: 'Romântico' },
        ],
      },
      layout: {
        type: 'select',
        default: 'card',
        label: 'Layout',
        options: [
          { value: 'card', label: 'Card' },
          { value: 'banner', label: 'Banner' },
          { value: 'split', label: 'Dividido' },
        ],
      },
      showDescription: {
        type: 'boolean',
        default: true,
        label: 'Mostrar Descrição',
      },
      showPercentage: {
        type: 'boolean',
        default: true,
        label: 'Mostrar Percentual',
      },
    },
    label: 'Resultados de Estilo',
    defaultProps: {
      title: 'Seu Estilo Predominante',
      showAllStyles: false,
      showGuideImage: true,
      guideImageUrl:
        'https://res.cloudinary.com/dqljyf76t/image/upload/v1745071344/GUIA_NATURAL_fzp6fc.webp',
      primaryStyle: 'Natural',
      layout: 'card',
      showDescription: true,
      showPercentage: true,
    },
  },

  {
    type: 'final-step',
    name: 'Etapa Final',
    description: 'Componente etapa final com propriedades configuráveis',
    category: 'Quiz',
    icon: Type,
    component: FinalStepEditor,
    properties: {
      stepNumber: {
        type: 'number',
        default: 21,
        label: 'Número da Etapa',
        min: 1,
        max: 50,
      },
      title: {
        type: 'string',
        default: 'Seu Estilo Predominante',
        label: 'Título',
      },
      subtitle: {
        type: 'string',
        default: 'Descubra seu estilo de moda único',
        label: 'Subtítulo',
      },
      showNavigation: {
        type: 'boolean',
        default: true,
        label: 'Mostrar Navegação',
      },
      showProgress: {
        type: 'boolean',
        default: true,
        label: 'Mostrar Progresso',
      },
      backgroundColor: {
        type: 'color',
        default: '#F9F5F1',
        label: 'Cor de Fundo',
      },
      accentColor: {
        type: 'color',
        default: '#B89B7A',
        label: 'Cor de Destaque',
      },
      layout: {
        type: 'select',
        default: 'centered',
        label: 'Layout',
        options: [
          { value: 'centered', label: 'Centralizado' },
          { value: 'split', label: 'Dividido' },
          { value: 'full', label: 'Tela Cheia' },
        ],
      },
    },
    label: 'Etapa Final',
    defaultProps: {
      stepNumber: 21,
      title: 'Seu Estilo Predominante',
      subtitle: 'Descubra seu estilo de moda único',
      showNavigation: true,
      showProgress: true,
      backgroundColor: '#F9F5F1',
      accentColor: '#B89B7A',
      layout: 'centered',
    },
  },

  {
    type: 'quiz-header',
    name: 'Cabeçalho de Quiz',
    description: 'Cabeçalho específico para questões do quiz com progresso',
    category: 'Quiz',
    icon: Type,
    component: QuizIntroHeaderBlock, // Reutiliza o mesmo componente
    properties: {
      logoUrl: {
        type: 'string',
        default:
          'https://res.cloudinary.com/dqljyf76t/image/upload/v1744911572/LOGO_DA_MARCA_GISELE_r14oz2.webp',
        label: 'URL do Logo',
      },
      logoAlt: {
        type: 'string',
        default: 'Logo',
        label: 'Alt do Logo',
      },
      logoWidth: {
        type: 'number',
        default: 80,
        label: 'Largura do Logo (px)',
        min: 40,
        max: 200,
      },
      logoHeight: {
        type: 'number',
        default: 80,
        label: 'Altura do Logo (px)',
        min: 40,
        max: 200,
      },
      progressValue: {
        type: 'number',
        default: 40,
        label: 'Progresso (%)',
        min: 0,
        max: 100,
      },
      progressMax: {
        type: 'number',
        default: 100,
        label: 'Progresso Máximo',
        min: 1,
        max: 100,
      },
      showBackButton: {
        type: 'boolean',
        default: true,
        label: 'Mostrar Botão Voltar',
      },
      showProgress: {
        type: 'boolean',
        default: true,
        label: 'Mostrar Progresso',
      },
      stepNumber: {
        type: 'string',
        default: '1 de 21',
        label: 'Número da Etapa',
      },
      spacing: {
        type: 'select',
        default: 'small',
        label: 'Espaçamento',
        options: [
          { value: 'none', label: 'Nenhum' },
          { value: 'small', label: 'Pequeno' },
          { value: 'medium', label: 'Médio' },
          { value: 'large', label: 'Grande' },
        ],
      },
      marginTop: {
        type: 'number',
        default: 0,
        label: 'Margem Superior (px)',
        min: 0,
        max: 100,
      },
      marginBottom: {
        type: 'number',
        default: 0,
        label: 'Margem Inferior (px)',
        min: 0,
        max: 100,
      },
    },
    label: 'Cabeçalho de Quiz',
    defaultProps: {
      logoUrl:
        'https://res.cloudinary.com/dqljyf76t/image/upload/v1744911572/LOGO_DA_MARCA_GISELE_r14oz2.webp',
      logoAlt: 'Logo',
      logoWidth: 80,
      logoHeight: 80,
      progressValue: 40,
      progressMax: 100,
      showBackButton: true,
      showProgress: true,
      stepNumber: '1 de 21',
      spacing: 'small',
      marginTop: 0,
      marginBottom: 0,
    },
  },

  {
    type: 'quiz-option',
    name: 'Opção de Quiz',
    description: 'Opção individual de resposta para questões do quiz',
    category: 'Quiz',
    icon: Square,
    component: BadgeInlineBlock, // Reutiliza componente de botão
    properties: {
      optionId: {
        type: 'string',
        default: 'option-1',
        label: 'ID da Opção',
      },
      label: {
        type: 'string',
        default: 'Opção de resposta',
        label: 'Texto da Opção',
      },
      value: {
        type: 'string',
        default: 'option-value',
        label: 'Valor da Opção',
      },
      variant: {
        type: 'select',
        default: 'default',
        label: 'Variante',
        options: [
          { value: 'default', label: 'Padrão' },
          { value: 'outline', label: 'Contorno' },
          { value: 'solid', label: 'Sólido' },
          { value: 'ghost', label: 'Fantasma' },
        ],
      },
      size: {
        type: 'select',
        default: 'large',
        label: 'Tamanho',
        options: [
          { value: 'small', label: 'Pequeno' },
          { value: 'medium', label: 'Médio' },
          { value: 'large', label: 'Grande' },
          { value: 'xl', label: 'Extra Grande' },
        ],
      },
      textAlign: {
        type: 'select',
        default: 'text-left',
        label: 'Alinhamento do Texto',
        options: [
          { value: 'text-left', label: 'Esquerda' },
          { value: 'text-center', label: 'Centro' },
          { value: 'text-right', label: 'Direita' },
        ],
      },
      marginBottom: {
        type: 'number',
        default: 12,
        label: 'Margem Inferior (px)',
        min: 0,
        max: 50,
      },
      borderRadius: {
        type: 'select',
        default: 'rounded-lg',
        label: 'Borda Arredondada',
        options: [
          { value: 'rounded-none', label: 'Nenhuma' },
          { value: 'rounded-sm', label: 'Pequena' },
          { value: 'rounded-md', label: 'Média' },
          { value: 'rounded-lg', label: 'Grande' },
          { value: 'rounded-xl', label: 'Extra Grande' },
        ],
      },
      backgroundColor: {
        type: 'color',
        default: '#ffffff',
        label: 'Cor de Fundo',
      },
      hoverColor: {
        type: 'color',
        default: '#F8F4F1',
        label: 'Cor de Hover',
      },
      selectedColor: {
        type: 'color',
        default: '#B89B7A',
        label: 'Cor de Seleção',
      },
      spacing: {
        type: 'select',
        default: 'small',
        label: 'Espaçamento',
        options: [
          { value: 'none', label: 'Nenhum' },
          { value: 'small', label: 'Pequeno' },
          { value: 'medium', label: 'Médio' },
          { value: 'large', label: 'Grande' },
        ],
      },
      marginTop: {
        type: 'number',
        default: 0,
        label: 'Margem Superior (px)',
        min: 0,
        max: 50,
      },
    },
    label: 'Opção de Quiz',
    defaultProps: {
      optionId: 'option-1',
      label: 'Opção de resposta',
      value: 'option-value',
      variant: 'default',
      size: 'large',
      textAlign: 'text-left',
      marginBottom: 12,
      borderRadius: 'rounded-lg',
      backgroundColor: '#ffffff',
      hoverColor: '#F8F4F1',
      selectedColor: '#B89B7A',
      spacing: 'small',
      marginTop: 0,
    },
  },
];

export const getCategories = (): string[] => {
  const categories = new Set<string>();
  blockDefinitions.forEach(block => {
    categories.add(block.category);
  });
  return Array.from(categories);
};

export const getBlocksByCategory = (category: string): BlockDefinition[] => {
  return blockDefinitions.filter(block => block.category === category);
};

export const getBlockByType = (type: string): BlockDefinition | undefined => {
  return blockDefinitions.find(block => block.type === type);
};
