#!/bin/bash

# ============================================================================
# Script para Aplicar Migration 20251028_optimize_component_queries.sql
# ============================================================================
# 
# ESTE SCRIPT DOCUMENTA COMO APLICAR A MIGRATION NO SUPABASE
# 
# ⚠️ IMPORTANTE: Migrations DDL (CREATE INDEX, CREATE FUNCTION) devem ser
#    aplicadas via Supabase Dashboard ou CLI, não via client SDK.
#
# ============================================================================

set -e

echo "🚀 GUIA DE APLICAÇÃO DA MIGRATION - Fase 4.2"
echo ""
echo "📋 Migration: 20251028_optimize_component_queries.sql"
echo "📂 Localização: supabase/migrations/20251028_optimize_component_queries.sql"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "OPÇÃO 1: Supabase Dashboard (RECOMENDADO)"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "1. Acesse: https://supabase.com/dashboard/project/your-supabase-project-ref"
echo "2. Navegue para: SQL Editor"
echo "3. Clique em: New Query"
echo "4. Cole o conteúdo do arquivo:"
echo "   supabase/migrations/20251028_optimize_component_queries.sql"
echo "5. Execute: RUN"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "OPÇÃO 2: Supabase CLI (se disponível)"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Se você tiver o Supabase CLI instalado:"
echo ""
echo "  cd supabase"
echo "  supabase db push --linked"
echo ""
echo "ou"
echo ""
echo "  npx supabase db push --linked"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "OPÇÃO 3: Script Node.js (em desenvolvimento)"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "  npm run db:migrate"
echo ""
echo "  (Nota: Este comando ainda não está implementado)"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "📊 O QUE SERÁ CRIADO:"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "✅ 4 Índices de Performance:"
echo "   - idx_components_funnel_step (funnel_id, step_number, order_index)"
echo "   - idx_components_type (component_type_key)"
echo "   - idx_components_stage (stage_id, order_index)"
echo "   - idx_components_active (is_active, funnel_id, step_number)"
echo ""
echo "✅ 2 RPC Functions:"
echo "   - batch_update_components(updates jsonb)"
echo "   - batch_reorder_components(component_ids uuid[], new_positions integer[])"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "📈 BENEFÍCIOS ESPERADOS:"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "⚡ ~70% melhoria em operações de batch update"
echo "⚡ ~50% melhoria em queries por funnel/step"
echo "⚡ Transações atômicas garantidas para batch operations"
echo "⚡ Melhor performance em reordenação de componentes"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "🔍 VERIFICAÇÃO PÓS-APLICAÇÃO:"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Execute no SQL Editor para verificar:"
echo ""
echo "-- Verificar índices criados"
echo "SELECT indexname FROM pg_indexes"
echo "WHERE tablename = 'component_instances'"
echo "  AND indexname LIKE 'idx_components_%';"
echo ""
echo "-- Verificar RPC functions criadas"
echo "SELECT routine_name FROM information_schema.routines"
echo "WHERE routine_schema = 'public'"
echo "  AND routine_name LIKE 'batch_%';"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "✅ PRÓXIMOS PASSOS (após aplicar migration):"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "1. Regenerar types TypeScript:"
echo "   npx supabase gen types typescript --linked > src/integrations/supabase/types.ts"
echo ""
echo "2. Ativar RPC no código:"
echo "   - Descomentar chamada RPC em funnelComponentsService.ts"
echo "   - Remover fallback Promise.all"
echo ""
echo "3. Testar em ambiente de desenvolvimento"
echo ""
echo "═══════════════════════════════════════════════════════════════"

# Verificar se o arquivo de migration existe
if [ ! -f "supabase/migrations/20251028_optimize_component_queries.sql" ]; then
    echo ""
    echo "❌ ERRO: Arquivo de migration não encontrado!"
    echo "   Esperado: supabase/migrations/20251028_optimize_component_queries.sql"
    exit 1
fi

echo ""
echo "✅ Arquivo de migration encontrado e pronto para aplicação!"
echo ""
echo "📝 Para visualizar o conteúdo da migration:"
echo "   cat supabase/migrations/20251028_optimize_component_queries.sql"
echo ""
