#!/bin/bash
##############################################################################
# Script Simplificado - Aplicar Migrations via Dashboard
# 
# Este script prepara os comandos SQL em um formato fácil de copiar e colar
# no SQL Editor do Supabase Dashboard
##############################################################################

echo "🔒 APLICAÇÃO DE MIGRATIONS DE SEGURANÇA"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "⚠️  A aplicação via API requer service_role key completa."
echo "    A chave atual (.env) pode não ter permissões suficientes."
echo ""
echo "📖 APLICAÇÃO MANUAL (RECOMENDADO):"
echo ""
echo "   1. Acesse o Dashboard:"
echo "      https://pwtjuuhchtbzttrzoutw.supabase.co"
echo ""
echo "   2. Vá para: SQL Editor (menu lateral)"
echo ""
echo "   3. Clique em 'New Query'"
echo ""
echo "   4. PRIMEIRA MIGRATION - Cole e execute:"
echo "      ┌────────────────────────────────────────────┐"
echo "      │ Arquivo: supabase/migrations/             │"
echo "      │          20251110_auth_hardening_rls.sql  │"
echo "      └────────────────────────────────────────────┘"
echo ""
read -p "      Pressione ENTER para ver o conteúdo... "
echo ""
cat supabase/migrations/20251110_auth_hardening_rls.sql | head -50
echo ""
echo "      ... (arquivo completo tem $(wc -l < supabase/migrations/20251110_auth_hardening_rls.sql) linhas)"
echo ""
echo "   5. SEGUNDA MIGRATION - Cole e execute:"
echo "      ┌────────────────────────────────────────────┐"
echo "      │ Arquivo: supabase/migrations/             │"
echo "      │          20251128_security_enhancements.sql│"
echo "      └────────────────────────────────────────────┘"
echo ""
read -p "      Pressione ENTER para ver o conteúdo... "
echo ""
cat supabase/migrations/20251128_security_enhancements.sql | head -50
echo ""
echo "      ... (arquivo completo tem $(wc -l < supabase/migrations/20251128_security_enhancements.sql) linhas)"
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo "✨ ATALHO RÁPIDO:"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "   Copie os arquivos para a área de transferência:"
echo ""
echo "   # Migration 1 (RLS Policies):"
echo "   cat supabase/migrations/20251110_auth_hardening_rls.sql | pbcopy"
echo "   # ou no Linux:"
echo "   cat supabase/migrations/20251110_auth_hardening_rls.sql | xclip -selection clipboard"
echo ""
echo "   # Migration 2 (Security Enhancements):"
echo "   cat supabase/migrations/20251128_security_enhancements.sql | pbcopy"
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo "🔍 VALIDAÇÃO PÓS-APLICAÇÃO:"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "   Após executar as migrations no Dashboard, valide:"
echo ""
echo "   node scripts/validate-security.mjs"
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo ""
