#!/bin/bash

echo "🧪 TESTE FUNCIONAL COMPLETO"
echo "============================"
echo ""

echo "📋 INSTRUÇÕES PARA TESTE MANUAL:"
echo ""
echo "1. 🌐 Abra o navegador em: http://localhost:8082/editor-fixed"
echo ""
echo "2. 🔍 Abra o DevTools (F12) e vá para a aba Console"
echo ""
echo "3. 🎯 Execute estes passos:"
echo "   a) Clique em um componente na sidebar (ex: Button, Input, Text)"
echo "   b) Arraste para o canvas (área central)"
echo "   c) Clique no componente no canvas para selecioná-lo"
echo "   d) Observe o painel de propriedades aparecer à direita"
echo "   e) Edite uma propriedade (ex: texto, cor, tamanho)"
echo ""
echo "4. 📊 O que observar no Console:"
echo "   ✅ Deve aparecer: '🔍 OptimizedPropertiesPanel: watchedValues changed:'"
echo "   ✅ Deve aparecer: '⏱️  OptimizedPropertiesPanel: debouncedValues changed:'"
echo "   ✅ Deve aparecer: '🚀 OptimizedPropertiesPanel: Calling onUpdateBlock with:'"
echo ""
echo "5. 🎨 O que observar no Canvas:"
echo "   ✅ O componente deve atualizar em tempo real (300ms após parar de digitar)"
echo "   ✅ Mudanças de texto devem aparecer imediatamente"
echo "   ✅ Mudanças de cor devem refletir no componente"
echo ""
echo "🔧 PROBLEMAS COMUNS E SOLUÇÕES:"
echo ""
echo "❌ Se não aparecer logs no console:"
echo "   → Verifique se selecionou um componente"
echo "   → Verifique se o painel de propriedades está visível"
echo ""
echo "❌ Se logs aparecem mas canvas não atualiza:"
echo "   → Problema no EditorContext.updateBlock"
echo "   → Verifique se o componente suporta a propriedade editada"
echo ""
echo "❌ Se nada acontece:"
echo "   → Verifique se o servidor está rodando"
echo "   → Recarregue a página (Ctrl+F5)"
echo ""
echo "🚀 TESTE AVANÇADO:"
echo "No console do navegador, você pode executar:"
echo "console.log('Estado atual dos blocos:', window.editorState);"
echo ""

# Verificar se o servidor está realmente rodando
if curl -s http://localhost:8082 > /dev/null; then
    echo "✅ SERVIDOR ATIVO: http://localhost:8082"
    echo "   🎯 Pronto para teste!"
else
    echo "❌ SERVIDOR INATIVO"
    echo "   Execute: npm run dev"
fi
