
// Mapeamento dos componentes inline realmente disponíveis
export const AVAILABLE_INLINE_COMPONENTS = {
  // Componentes básicos confirmados
  'TextInlineBlock': true,
  'BadgeInlineBlock': true,
  'ProgressInlineBlock': true,
  'ImageDisplayInlineBlock': true,
  'PricingCardInlineBlock': true,
  'TestimonialCardInlineBlock': true,
  'ResultHeaderInlineBlock': true,
  'StepHeaderInlineBlock': true,
  'StatInlineBlock': true,
  'LoadingAnimationBlock': true,
  'QuizIntroHeaderBlock': true,
  'CountdownInlineBlock': true,
  'StyleCardInlineBlock': true,
  'ResultCardInlineBlock': true,

  // Componentes que NÃO existem (causam erro de importação)
  'TestimonialsInlineBlock': false,
  'QuizOfferPricingInlineBlock': false,
  'BonusListInlineBlock': false,
  'QuizStartPageInlineBlock': false,
  'QuizPersonalInfoInlineBlock': false,
  'QuizExperienceInlineBlock': false,
  'QuizSkillsAssessmentInlineBlock': false,
  'QuizLeadershipStyleInlineBlock': false,
  'QuizCommunicationInlineBlock': false,
  'QuizProblemSolvingInlineBlock': false,
  'QuizGoalsInlineBlock': false,
  'QuizMotivationInlineBlock': false,
  'QuizWorkStyleInlineBlock': false,
  'QuizFeedbackInlineBlock': false,
  'QuizResultsInlineBlock': false,
  'QuizCertificateInlineBlock': false,
  'QuizLeaderboardInlineBlock': false,
  'QuizBadgesInlineBlock': false,
  'QuizEvolutionInlineBlock': false,
  'QuizNetworkingInlineBlock': false,
  'QuizDevelopmentPlanInlineBlock': false,
  'QuizGoalsDashboardInlineBlock': false,
  'QuizFinalResultsInlineBlock': false,
  'QuizOfferCTAInlineBlock': false
} as const;
